from core_data.cell import Cell
from core_data.cell_state import CellState
from core_data.cell_value import CellValue
from core_data.coordinate import Coordinate
from core_data.grid import Grid
from user_interface.display.display_grid import display_grid


def test_display_grid(capsys):
    cells = {
        Coordinate(0, 0, 9): Cell(CellValue(1, 9), CellState.PRE_FILLED),
        Coordinate(0, 1, 9): Cell(CellValue(2, 9), CellState.USER_FILLED),
        Coordinate(0, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(0, 3, 9): Cell(CellValue(4, 9), CellState.USER_FILLED),
        Coordinate(0, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(0, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(0, 6, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(0, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(0, 8, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(1, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(1, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(1, 2, 9): Cell(CellValue(9, 9), CellState.PRE_FILLED),
        Coordinate(1, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(1, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(1, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(1, 6, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(1, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(1, 8, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(2, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(2, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(2, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(2, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(2, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(2, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(2, 6, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(2, 7, 9): Cell(CellValue(1, 9), CellState.USER_FILLED),
        Coordinate(2, 8, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(3, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(3, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(3, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(3, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(3, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(3, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(3, 6, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(3, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(3, 8, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(4, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(4, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(4, 2, 9): Cell(CellValue(3, 9), CellState.PRE_FILLED),
        Coordinate(4, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(4, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(4, 5, 9): Cell(CellValue(8, 9), CellState.USER_FILLED),
        Coordinate(4, 6, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(4, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(4, 8, 9): Cell(CellValue(5, 9), CellState.PRE_FILLED),
        Coordinate(5, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(5, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(5, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(5, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(5, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(5, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(5, 6, 9): Cell(CellValue(6, 9), CellState.PRE_FILLED),
        Coordinate(5, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(5, 8, 9): Cell(CellValue(2, 9), CellState.PRE_FILLED),
        Coordinate(6, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(6, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(6, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(6, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(6, 4, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(6, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(6, 6, 9): Cell(CellValue(4, 9), CellState.PRE_FILLED),
        Coordinate(6, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(6, 8, 9): Cell(CellValue(9, 9), CellState.PRE_FILLED),
        Coordinate(7, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(7, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(7, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(7, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(7, 4, 9): Cell(CellValue(3, 9), CellState.PRE_FILLED),
        Coordinate(7, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(7, 6, 9): Cell(CellValue(1, 9), CellState.PRE_FILLED),
        Coordinate(7, 7, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(7, 8, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(8, 0, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(8, 1, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(8, 2, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED),
        Coordinate(8, 3, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(8, 4, 9): Cell(CellValue(5, 9), CellState.PRE_FILLED),
        Coordinate(8, 5, 9): Cell(CellValue(None, 9), CellState.USER_FILLED),
        Coordinate(8, 6, 9): Cell(CellValue(7, 9), CellState.PRE_FILLED),
        Coordinate(8, 7, 9): Cell(CellValue(8, 9), CellState.USER_FILLED),
        Coordinate(8, 8, 9): Cell(CellValue(None, 9), CellState.PRE_FILLED)
    }
    print()
    grid = Grid(cells, 9)
    display_grid(grid)

